{
    'name': 'Oduist Connect FreeSWITCH',
    'version': '18.0.1.7.12',
    'author': 'Oduist',
    'category': 'Phone',
    'summary': 'FreeSWITCH integration for Oduist Connect',
    'depends': ['connect', 'web'],
    'data': [
        'security/access_rules.xml',
        'data/fs_templates.xml',
        'data/parking_slots.xml',
        'views/endpoint_views.xml',
        'views/fs_template_views.xml',
        'views/user_views.xml',
        'views/gateway_views.xml',
        'views/outgoing_route_views.xml',
        'views/fs_fifo_views.xml',
        'views/fs_parking_slot_views.xml',
        'views/call_views.xml',
        'views/callflow_views_inherit.xml',
        'views/number_views_inherit.xml',
        'views/settings.xml',
    ],
    'assets': {
        'web.assets_backend': [
            'connect_freeswitch/static/src/css/phone_systray.css',
            'connect_freeswitch/static/src/js/verto_client.js',
            'connect_freeswitch/static/src/js/phone_systray.js',
            'connect_freeswitch/static/src/js/phone_panel.js',
            'connect_freeswitch/static/src/js/phone_service.js',
            'connect_freeswitch/static/src/js/parking_panel.js',
            'connect_freeswitch/static/src/xml/phone_systray.xml',
            'connect_freeswitch/static/src/xml/parking_panel.xml',
            'connect_freeswitch/static/src/widgets/phone_field/*',
        ],
    },
    'post_init_hook': 'post_init_hook',
    'installable': True,
    'application': False,
    'license': 'Other proprietary',
}
